services:


  service_api:
    build: .
    image: blog_api:1.0
    ports:
      - "80:8000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    depends_on:
      - service_db
    networks:
      - network_blog


  service_db:
    image: postgres:17.0-bookworm
    env_file:
      - ./.env
    volumes:
      - volume_blog_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    expose: 
      - 5432
    networks:
      - network_blog


volumes:
  volume_blog_data:


networks:
  network_blog:
